var LEVELS = [
  { map: [
    ".............",
    ".BB......BB..",
    ".............",
    ".B.TTTT.TT.B.",
    ".............",
    ".BBB.....BBB.",
    "......S......",
    "..B.BBB.B.B..",
    ".............",
    "...B.....B...",
    "...B.RRR.B...",
    ".............",
    "............."
  ], enemies: "BFBFBBBFBFBBBFBFBBBF" },
  { map: [
    ".............",
    "...B...S.B...",
    "..BB.RRR.BB..",
    ".BBB.RRR.BBB.",
    "......S......",
    "..BB.TTT.BB..",
    ".S.B.....B.S.",
    ".S.B.....B.S.",
    "......S......",
    "..B..RRR..B..",
    "..B...R...B..",
    ".............",
    "............."
  ], enemies: "BFBFBFBBPFBFBFBFBFBA" },
  { map: [
    ".............",
    "TTT.......TTT",
    "TTT...T...TTT",
    "...B.....B...",
    "..B..RRR..B..",
    "..B...R...B..",
    "..B..TST..B..",
    "..B..TST..B..",
    "..B...R...B..",
    "..B..RRR..B..",
    "...B.....B...",
    ".............",
    "............."
  ], enemies: "FBFBFBBBFBFBFBBBFBPF" },
  { map: [
    ".............",
    ".SS.......SS.",
    ".SB.......BS.",
    "..B...B...B..",
    "..B...S...B..",
    ".....TTT.....",
    "..S.......S..",
    ".....BBB.....",
    ".B.S..S.S..B.",
    "..B..RRR..B..",
    "..B.......B..",
    ".............",
    "............."
  ], enemies: "BFPFBFBBPFBFBFBAPFBA" },
  { map: [
    ".............",
    ".BB..RRR..BB.",
    ".....RRR.....",
    "..BB.RRR.BB..",
    "..B..RRR..B..",
    ".S...RRR...S.",
    "......S......",
    "..B..RRR..B..",
    "..BB.RRR.BB..",
    ".....RRR.....",
    ".BB..RRR..BB.",
    ".............",
    "............."
  ], enemies: "FBFAPBFBPFBFBBBAPFBF" },
  { map: [
    ".............",
    ".BBB.SSS.BBB.",
    ".B.B..S..B.B.",
    ".B.........B.",
    "..S..TTT..S..",
    ".....BBB.....",
    "..B..TTT..B..",
    ".....BBB.....",
    "..S..RRR..S..",
    ".B.R.TT..R.B.",
    "...S.RRR.S...",
    ".............",
    "............."
  ], enemies: "PFBFAFBFBBPFAFBFBBPF" },
  { map: [
    ".............",
    "S.BB.SSS.BB.S",
    "S.B.......B.S",
    "...B.....B...",
    "...T.SSS.T...",
    "TTT.S....STTT",
    "TTT...S...TTT",
    "TTT...S...TTT",
    "TTT.S....STTT",
    "...T.SSS.T...",
    "...B.....B...",
    ".............",
    "............."
  ], enemies: "PFAPFBFBBPFAPFBBPFBP" },
  { map: [
    ".............",
    ".TTT.....TTT.",
    "......S......",
    "..BBR...RBB..",
    "..BBRRRRRBB..",
    "...B.R.R.B...",
    "...B.RRR.B...",
    "....R...R....",
    ".....S.S.....",
    ".BB.......BB.",
    "..T..TTT..T..",
    ".............",
    "............."
  ], enemies: "BAAFBBFAPBFAFBBBBAFP" },
  { map: [
    ".............",
    "S.BB.....BB.S",
    "S.B...B...B.S",
    "..BB......BB.",
    "..B..SSS..B..",
    ".BB.......BB.",
    ".....BBB.....",
    ".....TTT.....",
    ".BB.......BB.",
    "R.BB.....BB.R",
    "...S.....S...",
    ".............",
    "............."
  ], enemies: "PAFBFPBAPBFAFBBPBFFA" },
  { map: [
    ".............",
    "..BR..S..RB..",
    "..BBR.S.RBB..",
    "...RRR.RRR...",
    ".....RRR.....",
    "TT..SS.SS..TT",
    "TTTT.S.S.TTTT",
    "TTTT.S.S.TTTT",
    "TT..SS.SS..TT",
    ".....RRR.....",
    "...RRR.RRR...",
    ".............",
    "............."
  ], enemies: "FAPBAPFAFBBAPBFAPBFA" },
  { map: [
    ".............",
    "BBB.BBBBB.BBB",
    "BBB.......BBB",
    "BB.B.TTT.B.BB",
    "B..B.....B..B",
    ".S.S.....S.S.",
    "..RB.TTT.BR..",
    ".....BBB.....",
    "..RB.TTT.BR..",
    ".S.S.....S.S.",
    "B..B.....B..B",
    ".............",
    "............."
  ], enemies: "APFAFBPAPBPFBBAPBPFA" },
  { map: [
    ".............",
    "SSS.SSSSS.SSS",
    "SSS.S...S.SSS",
    "SS.........SS",
    "..S..BBB..S..",
    "....STTTS....",
    "..B.......B..",
    "..B.......B..",
    "...B.BBB.B...",
    "....STTTS....",
    "S..B.....B..S",
    ".............",
    "............."
  ], enemies: "PFAPFAPBAPFAPBPAPFAF" }
];
if (typeof module !== "undefined" && module.exports) module.exports = LEVELS;
